# Settings Server
server:
  port: 8090

# mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# Settings Spring
spring:
  # Database
  datasource:
    url: jdbc:mariadb://localhost:3306/local_mariadb?serverTimezone=JST
    username: admin
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  # Logging Color
  output:
    ansi:
      enabled: always
  # Redis
  redis:
    host: 127.0.0.1
    port: 6379
  # Mail
  mail:
    host: stmp.gmail.com
    username: spring-base-batch@gmail.com
    password:
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 1025

redis:
  key: return-book